Changed active look to enabled looks.
autodesk-forks/MaterialX pull request #1158
Opened 2021-04-01 16:52 UTC by feldstj

2021-04-01 16:53 UTC, feldstj commented on source/MaterialXCore/Look.cpp
> +LookVec LookGroup::getAllEnabledLooks() const
Wasn't sure what to call this because getEnabledLooks was taken, open to suggested names.

2021-04-01 17:27 UTC, bernardkwok requested changes

2021-04-01 17:27 UTC, bernardkwok commented on source/MaterialXCore/Look.cpp
> +const string LookGroup::ENABLED_ATTRIBUTE = "enabled";
You can't change this string as it's defined in the spec. If it's changed we need an upgrade path.

2021-04-01 17:27 UTC, bernardkwok commented on source/MaterialXCore/Look.h
> +    const string& getEnabledLooks() const
Perhaps getEnabledLookString() and the other is getEnabledLooks().

2021-04-06 14:48 UTC, bernardkwok approved these changes
Looks good. Minor nitpick on string constants.

2021-04-06 14:48 UTC, bernardkwok commented on source/MaterialXCore/Document.cpp
> +            if (lookGroup->hasAttribute("active"))
Nitpicks: Declare a constant string for "active"  outside the look, and `string active` I assume should be const.

2021-04-06 15:15 UTC, merged