Initial support for export.
autodesk-forks/MaterialX pull request #1177
Opened 2021-04-27 18:30 UTC by feldstj

2021-04-27 18:32 UTC, feldstj commented on resources/LookDev/defaultLook.mtlx
> +  <lookgroup name="defaultLookGroup" looks="defaultLook" enabled="defaultLook" />
defaultLook.mtlx fix

2021-04-27 18:32 UTC, feldstj commented on resources/Materials/TestSuite/stdlib/looks/looks.mtlx
> +<?xml version="1.0"?>
Needed for test case.

2021-04-27 18:32 UTC, feldstj commented on source/MaterialXRuntime/RtFileIo.cpp
> +void mergeLooks(DocumentPtr document)
Function that merges the look information into a single look.

2021-04-27 18:32 UTC, feldstj commented on source/MaterialXRuntime/RtFileIo.cpp
> +void RtFileIo::exportDocument(std::ostream& stream, const RtExportOptions* options)
Export routines.

2021-04-27 18:32 UTC, feldstj commented on source/MaterialXRuntime/RtFileIo.h
> +/// @class RtExportOptions
RtExportOptions.

2021-04-27 18:32 UTC, feldstj commented on source/MaterialXTest/MaterialXRuntime/Runtime.cpp
> +TEST_CASE("Export", "[runtime]")
Simple test case.

2021-04-27 19:00 UTC, bernardkwok requested changes
Some logic comments and also that we require export at the core level and not inside runtime
for general usage.

2021-04-28 13:23 UTC, feldstj commented on source/MaterialXRuntime/RtFileIo.cpp
> +        if (looksInLookGroup.count(look->getName()) == 0)
Ok, I'll add the stray looks first. I actually like == 0 better to be honest, I think it's more clear.

2021-04-28 17:37 UTC, bernardkwok commented on source/MaterialXRuntime/RtFileIo.cpp
> +            lookNames.push_back(look->getName());
Guess you could iterate in reverse. If not guess leave it as is.

2021-04-28 17:37 UTC, bernardkwok commented on source/MaterialXRuntime/RtFileIo.cpp
> +        if (looksInLookGroup.count(look->getName()) == 0)
Think we use the "!" convention so just mentiong to stick to whatever the convention is.

2021-04-28 17:51 UTC, feldstj commented on source/MaterialXRuntime/RtFileIo.cpp
> +        if (looksInLookGroup.count(look->getName()) == 0)
I just did a search in the MaterialX repo for .count() and it seems that both are used about equally.

2021-04-28 19:43 UTC, bernardkwok approved these changes
Looks good.

2021-04-28 19:43 UTC, bernardkwok commented on source/MaterialXCore/Document.cpp
> +    // Append look names that don't belong to the mainLook to lookNames
"append the looks which are not the main look."

2021-04-28 19:43 UTC, bernardkwok commented on source/MaterialXFormat/XmlIo.cpp
> +static void mergeLooks(DocumentPtr doc, const XmlExportOptions* exportOptions)
We should move this to the anonymous namespace at the top and make non-static.

2021-04-29 14:56 UTC, merged