Fix node graph and node definition reference when publishing compounds.
autodesk-forks/MaterialX pull request #1298
Opened 2021-08-25 12:55 UTC by lyuborusev

The definition that is set for the node graph shall not include the namespace prefix.

2021-08-30 12:57 UTC, feldstj approved these changes

2021-09-08 15:06 UTC, bernardkwok approved these changes

2021-09-08 15:14 UTC, bernardkwok requested changes
This is partially correct. It now saves a nodedef with the namespace qualfier as part of it's name which is invalid. e.g. published definition where `adsk:ND_zzzz_color3_1.0_adsk` is invalid.
```
<?xml version="1.0"?>
<materialx version="1.38">
  <nodedef name="adsk:ND_zzzz_color3_1.0_adsk" node="zzzz" version="1.0" isdefaultversion="true" namespace="adsk">
    <input name="file" type="filename" uniform="true" value="" />
    <output name="out" type="color3" value="0, 0, 0" />
  </nodedef>
  <nodegraph name="NG_zzzz_color3_1.0_adsk" xpos="688.708" ypos="-467.624" ldx_io_nodes="&amp;lt;?xml version=&quot;1.0&quot;?&amp;gt;&#10;&amp;lt;materialx version=&quot;1.38&quot;&amp;gt;&#10;  &amp;lt;layout name=&quot;io&quot; type=&quot;&quot; /&amp;gt;&#10;&amp;lt;/materialx&amp;gt;&#10;" namespace="adsk" nodedef="adsk:ND_zzzz_color3_1.0_adsk">
    <input name="file" type="filename" uniform="true" value="" />
    <image name="image" type="color3" nodedef="ND_image_color3" xpos="-128" ypos="-127">
      <input name="file" type="filename" uniform="true" interfacename="file" uivisible="true" />
    </image>
    <output name="out" type="color3" nodename="image" />
  </nodegraph>
</materialx>
```

2021-09-08 18:21 UTC, bernardkwok commented
After some tracing this appears to be the current overall logic.

![image](https://user-images.githubusercontent.com/14275104/132562926-86dbb246-0a2c-49d6-add5-641b16efed1b.png)

The "patch" seems to be to create an RtNodeDef which is using the qualified name. This allows the simple lookup by name of RtNodeGraph to RtNodeDef to "work" partially.

If we continue with this logic then the write of RtNodeDef to NodeDef should remove any namespaces which area already specified otherwise the qualfied name of these nodedefs would become `<namespace>:<namespace>:<name>` which will fail
at look up time.

A possible longer term solution is to use the same mechanism which is Core which is to lookup using qualfied names in all places, or only use pointer associations for cross referencing. I'm still unsure how this got "broken", but my hunch is that some logic reordering resulted in the MTLX content being written w/o qualfied names and then the definition is registered as a RtNodeDef with a qualified name.

2021-09-08 20:57 UTC, feldstj approved these changes

2021-09-08 21:02 UTC, bernardkwok approved these changes

2021-09-08 21:09 UTC, merged